# api 크롤링

기존의 크롤링 방식은 

1. 내가 직접 홈페이지에 브라우저를 켜서 접근하거나(selenium) 

혹은 

2. 파이썬 자체적으로 호출을 요청해서(requests)

데이터를 가지고 오는 방식이었습니다.

이 방식은 서버에 부하가 많이 갈 뿐더러 나에게 필요없는 데이터까지 한 번에 호출해서 가져오는 문제가 있습니다.

따라서 서비스 제공자측에서는 서버 부하를 줄이고, 사용자에게 맞춤형을 데이터를 제공하기 위해 api서버를 운영합니다.

api서버는 인가된 데이터만을 개발자에게 넘겨서 서버도 안정적으로 유지하며(횟수 제한이 있는 사이트도 많습니다. 라이엇 데이터는 1초에 5회, 2분에 100회로 제한됩니다.) 

필요없는 동영상자료나 그림자료를 호출하지 않으므로 트래픽을 줄일 수 있습니다.



api 서버 접근시 보통 urllib.request 를 이용하게 됩니다.

In [1]:
# 사이트에 자료 요청
import urllib.request 
# json 데이터 핸들링
import json 
# DataFrame 자료형 활용
import pandas as pd 
# json 데이터를 pandas DataFrame으로 변환
from pandas.io.json import json_normalize

# 영진위 api신청

http://www.kobis.or.kr/kobisopenapi/homepg/main/main.do

1. 접속 후 가입 및 로그인

2. 키발급 탭에서 키 발급하기

3. 요청 api종류 보고 요청양식 및 데이터 확인하기

In [2]:
api_key = "f5eef3421c602c6cb7ea224104795888" # 발급받은 키만 복붙하세요
request_date = "20220622" # 조회날짜를  xxxxyydd 20220623 형식으로 넣어주세요
url = "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=%s&targetDt=%s" % (api_key, request_date)
print(url)

http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20220622

# json데이터를 팬더스 데이터프레임으로 변환

api 데이터는 보통 json(JavaScript Object Notation) 타입으로 받아집니다.

쉽게 말하면 자바스크립트 데이터를 전달하기 좋게 설정한 자료형인데

파이썬의 딕셔너리와 거의 같다고 보시면 됩니다.

따라서 json 데이터를 팬더스 데이터로 변환한다는 것은 사실상

딕셔너리 데이터를 팬더스 데이터프레임으로 변환하는것입니다.

In [3]:
# 위의 url 변수를 이용해 데이터를 요청합니다.
r = urllib.request.urlopen(url)

# 요청 페이지의 결과 데이터를 파이썬 내부 데이터로 바꿉니다.
json_raw = r.read()

In [4]:
# b'~~~~~~~'로 시작하는 이 데이터는 파이썬에서 byte자료형으로 처리되고
# 데이터프레임으로는 바로 변환이 불가능합니다.
json_raw

b'{"boxOfficeResult":{"boxofficeType":"\xec\x9d\xbc\xeb\xb3\x84 \xeb\xb0\x95\xec\x8a\xa4\xec\x98\xa4\xed\x94\xbc\xec\x8a\xa4","showRange":"20220622~20220622","dailyBoxOfficeList":[{"rnum":"1","rank":"1","rankInten":"0","rankOldAndNew":"NEW","movieCd":"20194376","movieNm":"\xed\x83\x91\xea\xb1\xb4: \xeb\xa7\xa4\xeb\xb2\x84\xeb\xa6\xad","openDt":"2022-06-22","salesAmt":"1976049530","salesShare":"54.3","salesInten":"1976049530","salesChange":"100","salesAcc":"2716938360","audiCnt":"188312","audiInten":"188312","audiChange":"100","audiAcc":"253016","scrnCnt":"1975","showCnt":"9158"},{"rnum":"2","rank":"2","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20224882","movieNm":"\xeb\xa7\x88\xeb\x85\x80(\xe9\xad\x94\xe5\xa5\xb3) Part2. The Other One","openDt":"2022-06-15","salesAmt":"836476290","salesShare":"23.0","salesInten":"-253649090","salesChange":"-23.3","salesAcc":"18226409650","audiCnt":"82691","audiInten":"-25491","audiChange":"-23.6","audiAcc":"1769461","scrnCnt":"976","showCnt":"3502"},{"rnum":"3","rank":"3","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20204548","movieNm":"\xeb\xb2\x94\xec\xa3\x84\xeb\x8f\x84\xec\x8b\x9c 2","openDt":"2022-05-18","salesAmt":"577713370","salesShare":"15.9","salesInten":"-158550060","salesChange":"-21.5","salesAcc":"120660923940","audiCnt":"57874","audiInten":"-15988","audiChange":"-21.6","audiAcc":"11671470","scrnCnt":"774","showCnt":"2531"},{"rnum":"4","rank":"4","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20206257","movieNm":"\xeb\xb8\x8c\xeb\xa1\x9c\xec\xbb\xa4","openDt":"2022-06-08","salesAmt":"96967760","salesShare":"2.7","salesInten":"-120719520","salesChange":"-55.5","salesAcc":"11616358360","audiCnt":"9992","audiInten":"-12366","audiChange":"-55.3","audiAcc":"1160649","scrnCnt":"449","showCnt":"674"},{"rnum":"5","rank":"5","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20223839","movieNm":"\xeb\xb2\x84\xec\xa6\x88 \xeb\x9d\xbc\xec\x9d\xb4\xed\x8a\xb8\xec\x9d\xb4\xec\x96\xb4","openDt":"2022-06-15","salesAmt":"34719200","salesShare":"1.0","salesInten":"-99957740","salesChange":"-74.2","salesAcc":"2493961690","audiCnt":"3952","audiInten":"-8455","audiChange":"-68.1","audiAcc":"233278","scrnCnt":"287","showCnt":"375"},{"rnum":"6","rank":"6","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20206061","movieNm":"\xec\xa5\xac\xeb\x9d\xbc\xea\xb8\xb0 \xec\x9b\x94\xeb\x93\x9c: \xeb\x8f\x84\xeb\xaf\xb8\xeb\x8b\x88\xec\x96\xb8","openDt":"2022-06-01","salesAmt":"21223800","salesShare":"0.6","salesInten":"-76011160","salesChange":"-78.2","salesAcc":"28777337910","audiCnt":"2271","audiInten":"-7685","audiChange":"-77.2","audiAcc":"2788530","scrnCnt":"117","showCnt":"141"},{"rnum":"7","rank":"7","rankInten":"0","rankOldAndNew":"NEW","movieCd":"20224757","movieNm":"\xeb\xa3\xb8 \xec\x89\x90\xec\x96\xb4\xeb\xa7\x81","openDt":"2022-06-22","salesAmt":"13283560","salesShare":"0.4","salesInten":"13283560","salesChange":"100","salesAcc":"33442560","audiCnt":"1586","audiInten":"1586","audiChange":"100","audiAcc":"3937","scrnCnt":"122","showCnt":"190"},{"rnum":"8","rank":"8","rankInten":"12","rankOldAndNew":"OLD","movieCd":"20178501","movieNm":"\xeb\x8b\x88 \xeb\xb6\x80\xeb\xaa\xa8 \xec\x96\xbc\xea\xb5\xb4\xec\x9d\xb4 \xeb\xb3\xb4\xea\xb3\xa0 \xec\x8b\xb6\xeb\x8b\xa4","openDt":"2022-04-27","salesAmt":"5090000","salesShare":"0.1","salesInten":"3590000","salesChange":"239.3","salesAcc":"3912819280","audiCnt":"1015","audiInten":"715","audiChange":"238.3","audiAcc":"409303","scrnCnt":"3","showCnt":"4"},{"rnum":"9","rank":"9","rankInten":"5","rankOldAndNew":"OLD","movieCd":"20199500","movieNm":"\xeb\x9c\xa8\xea\xb1\xb0\xec\x9a\xb4 \xed\x94\xbc","openDt":"2022-03-23","salesAmt":"5000000","salesShare":"0.1","salesInten":"2500000","salesChange":"100","salesAcc":"3776252970","audiCnt":"1000","audiInten":"500","audiChange":"100","audiAcc":"396788","scrnCnt":"4","showCnt":"5"},{"rnum":"10","rank":"9","rankInten":"5","rankOldAndNew":"OLD","movieCd":"20212783","movieNm":"\xeb\xa1\x9c\xec\x8a\xa4\xed\x8a\xb8 \xec\x8b\x9c\xed\x8b\xb0","openDt":"2022-04-20","salesAmt":"5000000","salesShare":"0.1","salesInten":"2500000","salesChange":"100","salesAcc":"1006394850","audiCnt":"1000","audiInten":"500","audiChange":"100","audiAcc":"109848","scrnCnt":"4","showCnt":"5"}]}}'

In [5]:
# 바이트자료형임을 확인
type(json_raw)

bytes

In [6]:
# 따라서 utf-8 형식으로 고쳐줘야 합니다. .decode()를 이용합니다.
# encode => 우리가 쓰는 문자를 컴퓨터가 쓰는 형태로 변환
# decode => 컴퓨터가 쓰는 형태의 문자를 우리가 쓰는 형태로 변환
json_utf8 = json_raw.decode("utf-8")

In [8]:
# 딕셔너리 구조를 유지하고 있는 문자로 변환됨
type(json_utf8)

str

In [7]:
json_utf8

'{"boxOfficeResult":{"boxofficeType":"일별 박스오피스","showRange":"20220622~20220622","dailyBoxOfficeList":[{"rnum":"1","rank":"1","rankInten":"0","rankOldAndNew":"NEW","movieCd":"20194376","movieNm":"탑건: 매버릭","openDt":"2022-06-22","salesAmt":"1976049530","salesShare":"54.3","salesInten":"1976049530","salesChange":"100","salesAcc":"2716938360","audiCnt":"188312","audiInten":"188312","audiChange":"100","audiAcc":"253016","scrnCnt":"1975","showCnt":"9158"},{"rnum":"2","rank":"2","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20224882","movieNm":"마녀(魔女) Part2. The Other One","openDt":"2022-06-15","salesAmt":"836476290","salesShare":"23.0","salesInten":"-253649090","salesChange":"-23.3","salesAcc":"18226409650","audiCnt":"82691","audiInten":"-25491","audiChange":"-23.6","audiAcc":"1769461","scrnCnt":"976","showCnt":"3502"},{"rnum":"3","rank":"3","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20204548","movieNm":"범죄도시 2","openDt":"2022-05-18","salesAmt":"577713370","salesShare":"15.9","salesInten":"-158550060","salesChange":"-21.5","salesAcc":"120660923940","audiCnt":"57874","audiInten":"-15988","audiChange":"-21.6","audiAcc":"11671470","scrnCnt":"774","showCnt":"2531"},{"rnum":"4","rank":"4","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20206257","movieNm":"브로커","openDt":"2022-06-08","salesAmt":"96967760","salesShare":"2.7","salesInten":"-120719520","salesChange":"-55.5","salesAcc":"11616358360","audiCnt":"9992","audiInten":"-12366","audiChange":"-55.3","audiAcc":"1160649","scrnCnt":"449","showCnt":"674"},{"rnum":"5","rank":"5","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20223839","movieNm":"버즈 라이트이어","openDt":"2022-06-15","salesAmt":"34719200","salesShare":"1.0","salesInten":"-99957740","salesChange":"-74.2","salesAcc":"2493961690","audiCnt":"3952","audiInten":"-8455","audiChange":"-68.1","audiAcc":"233278","scrnCnt":"287","showCnt":"375"},{"rnum":"6","rank":"6","rankInten":"-1","rankOldAndNew":"OLD","movieCd":"20206061","movieNm":"쥬라기 월드: 도미니언","openDt":"2022-06-01","salesAmt":"21223800","salesShare":"0.6","salesInten":"-76011160","salesChange":"-78.2","salesAcc":"28777337910","audiCnt":"2271","audiInten":"-7685","audiChange":"-77.2","audiAcc":"2788530","scrnCnt":"117","showCnt":"141"},{"rnum":"7","rank":"7","rankInten":"0","rankOldAndNew":"NEW","movieCd":"20224757","movieNm":"룸 쉐어링","openDt":"2022-06-22","salesAmt":"13283560","salesShare":"0.4","salesInten":"13283560","salesChange":"100","salesAcc":"33442560","audiCnt":"1586","audiInten":"1586","audiChange":"100","audiAcc":"3937","scrnCnt":"122","showCnt":"190"},{"rnum":"8","rank":"8","rankInten":"12","rankOldAndNew":"OLD","movieCd":"20178501","movieNm":"니 부모 얼굴이 보고 싶다","openDt":"2022-04-27","salesAmt":"5090000","salesShare":"0.1","salesInten":"3590000","salesChange":"239.3","salesAcc":"3912819280","audiCnt":"1015","audiInten":"715","audiChange":"238.3","audiAcc":"409303","scrnCnt":"3","showCnt":"4"},{"rnum":"9","rank":"9","rankInten":"5","rankOldAndNew":"OLD","movieCd":"20199500","movieNm":"뜨거운 피","openDt":"2022-03-23","salesAmt":"5000000","salesShare":"0.1","salesInten":"2500000","salesChange":"100","salesAcc":"3776252970","audiCnt":"1000","audiInten":"500","audiChange":"100","audiAcc":"396788","scrnCnt":"4","showCnt":"5"},{"rnum":"10","rank":"9","rankInten":"5","rankOldAndNew":"OLD","movieCd":"20212783","movieNm":"로스트 시티","openDt":"2022-04-20","salesAmt":"5000000","salesShare":"0.1","salesInten":"2500000","salesChange":"100","salesAcc":"1006394850","audiCnt":"1000","audiInten":"500","audiChange":"100","audiAcc":"109848","scrnCnt":"4","showCnt":"5"}]}}'

In [10]:
# json.loads(딕셔너리 형태의 문자열 자료)
# 딕셔너리 형태로 적힌 문자열 자료를 딕셔너리형으로 변환
json_complete = json.loads(json_utf8)

In [11]:
# 딕셔너리(json) 변환 완료 확인
type(json_complete)

dict

In [12]:
# json_normalize(딕셔너리 자료)
# 딕셔너리 자료를 데이터프레임 형태로 변환해줌.
pd.json_normalize(json_complete)

,boxOfficeResult.boxofficeType,boxOfficeResult.showRange,boxOfficeResult.dailyBoxOfficeList
0,일별 박스오피스,20220622~20220622,"[{'rnum': '1', 'rank': '1', 'rankInten': '0', ..."

In [18]:
# boxOfficeResult.dailyBoxOfficeList 컬럼 내부에 딕셔너리가 여럿 묶인 리스트가 보이므로
# boxOfficeResult.dailyBoxOfficeList 컬럼을 타겟으로 데이터프레임화 합니다.
box_result = pd.json_normalize(json_complete['boxOfficeResult']['dailyBoxOfficeList'])

In [24]:
# json_normalize()는 pd.DataFrame() 으로 대체 가능합니다.
pd.DataFrame(json_complete)

                                                      boxOfficeResult
boxofficeType                                                일별 박스오피스
dailyBoxOfficeList  [{'rnum': '1', 'rank': '1', 'rankInten': '0', ...
showRange                                           20220622~20220622

API 크롤링으로 서비스 제공시

사용자가 조회할때마다 매번 API서버에 요청을 넣어서 데이터를 가져오면

호출횟수를 금방 소모하게 됩니다.

따라서, 보통 API를 활용한 서비스는 미리 데이터를 DB에 적재해놓고

사용자가 요청시 내 DB에 있는 데이터를 우선적으로 보여주고, 없으면 외부서버에 

요청해서 내 DB에 INSERT한 다음 다시 내 DB데이터를 사용자에게 보여줍니다.

In [25]:
url

'http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=f5eef3421c602c6cb7ea224104795888&targetDt=20220622'

날짜 데이터는 28일까지인 달(2월), 30일까지인 달, 31일까지인 달 들이 있어서

단순히 문자열에 1씩 더하거나 날짜처리를 하기도 어렵고

위의 처리를 다 했다고 해도 4년에 1번 윤달이 있습니다(2월 29일)

그래서, 날짜는 전적으로 날짜데이터를 이용해 처리해야만 합니다.

파이썬에서는 datetime을 이용해 처리합니다.(자바는 java.util.Date를 써서 처리)

In [27]:
import time
import datetime # 파이썬 날짜 자료형

In [41]:
start_datetime = datetime.datetime(2021, 8, 9) # 년 월 일 순으로 넣어줍니다.
# 형식 바꾸기
target_date = start_datetime.strftime('%Y%m%d') #영진위 형식으로 변경
print(target_date)
# 날짜 하루 올리기
next_datetime = start_datetime - datetime.timedelta(days=1)
next_datetime

20210809

datetime.datetime(2021, 8, 8, 0, 0)

In [45]:
target_dates = ['20220805','20220806','20220807']
# 날짜는 시작날짜와 + 며칠 을 처리할지 결정할 수 있습니다.
# 3일치 데이터를 얻은 다음 to_csv나 to_excel로 저장해주세요.

# 반복문과 append를 이용해서 3일치 데이터를 요청해서 합쳐보세요.
# target_date 컬럼에 조회 날짜를 추가해주세요.
# 빈 데이터프레임을 하나 생성해놓고(pd.DataFrame())
merged_data = pd.DataFrame()
for date in target_dates:
    api_key = "f5eef3421c602c6cb7ea224104795888" # 발급받은 키만 복붙하세요
    request_date = date # 조회날짜를  xxxxyydd 20220623 형식으로 넣어주세요
    url = "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=%s&targetDt=%s" % (api_key, request_date)
    # 위의 url 변수를 이용해 데이터를 요청합니다.
    r = urllib.request.urlopen(url)

    # 요청 페이지의 결과 데이터를 파이썬 내부 데이터로 바꿉니다.
    json_raw = r.read()
    
    json_utf8 = json_raw.decode("utf-8")
    # json.loads(딕셔너리 형태의 문자열 자료)
    # 딕셔너리 형태로 적힌 문자열 자료를 딕셔너리형으로 변환
    json_complete = json.loads(json_utf8)
    box_result = pd.json_normalize(json_complete['boxOfficeResult']['dailyBoxOfficeList'])
    # box_result에 날짜 컬럼 추가해 날짜 정보 넣기
    box_result['date'] = request_date
    merged_data = pd.concat([merged_data, box_result])
merged_data

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,date
0,1,1,1,OLD,20209343,한산: 용의 출현,2022-07-27,2565562184,41.6,530997656,26.1,37567540644,250628,41281,19.7,3692260,1530,6343,20220805
1,2,2,-1,OLD,20196410,비상선언,2022-08-03,2094794151,34.0,71338791,3.5,7693545482,213574,-8542,-3.8,794759,1718,7281,20220805
2,3,3,1,OLD,20194376,탑건: 매버릭,2022-06-22,504483247,8.2,148299938,41.6,77905793874,46942,12422,36,7305829,605,1238,20220805
3,4,4,-1,OLD,20205362,미니언즈2,2022-07-20,413915957,6.7,948579,0.2,17794010400,43092,-1769,-3.9,1837974,783,1595,20220805
4,5,5,0,OLD,20225190,뽀로로 극장판 드래곤캐슬 대모험,2022-07-28,167553618,2.7,-5960802,-3.4,2909201168,18088,-1181,-6.1,312147,537,779,20220805
5,6,6,0,OLD,20209654,헤어질 결심,2022-06-29,142017614,2.3,34703455,32.3,18014179742,13226,3017,29.6,1741846,265,432,20220805
6,7,7,0,OLD,20208446,외계+인 1부,2022-07-20,113278760,1.8,22370761,24.6,15283635796,11557,2267,24.4,1466380,407,576,20220805
7,8,8,0,OLD,20226107,극장판 도라에몽: 진구의 우주소전쟁 리틀스타워즈 2021,2022-08-03,50015320,0.8,-4063959,-7.5,192992299,5268,-678,-11.4,20861,362,513,20220805
8,9,9,0,OLD,20225237,명탐정 코난: 할로윈의 신부,2022-07-13,27421500,0.4,3966180,16.9,4509968774,2517,232,10.2,434341,75,94,20220805
9,10,10,26,OLD,20224882,마녀(魔女) Part2. The Other One,2022-06-15,12398000,0.2,11939500,2604,28919650670,2433,2378,4323.6,2806159,20,20,20220805
0,1,1,0,OLD,20209343,한산: 용의 출현,2022-07-27,4833705390,45.1,2268143206,88.4,42401246034,465418,214790,85.7,4157678,1637,6816,20220806
1,2,2,0,OLD,20196410,비상선언,2022-08-03,3450072301,32.2,1355278150,64.7,11143617783,324480,110906,51.9,1119239,1619,6862,20220806
2,3,3,0,OLD,20194376,탑건: 매버릭,2022-06-22,813824500,7.6,309341253,61.3,78719618374,74351,27409,58.4,7380180,631,1310,20220806
3,4,4,0,OLD,20205362,미니언즈2,2022-07-20,675153336,6.3,261237379,63.1,18469163736,68046,24954,57.9,1906020,818,1734,20220806
4,5,5,0,OLD,20225190,뽀로로 극장판 드래곤캐슬 대모험,2022-07-28,262266899,2.4,94713281,56.5,3171468067,27419,9331,51.6,339566,581,863,20220806
5,6,6,1,OLD,20208446,외계+인 1부,2022-07-20,222289537,2.1,109010777,96.2,15505925333,18867,7310,63.3,1485247,396,548,20220806
6,7,7,-1,OLD,20209654,헤어질 결심,2022-06-29,201851173,1.9,59833559,42.1,18216030915,18001,4775,36.1,1759847,278,438,20220806
7,8,8,0,OLD,20226107,극장판 도라에몽: 진구의 우주소전쟁 리틀스타워즈 2021,2022-08-03,75556800,0.7,25541480,51.1,268549099,7655,2387,45.3,28516,360,472,20220806
8,9,9,0,OLD,20225237,명탐정 코난: 할로윈의 신부,2022-07-13,44011900,0.4,16590400,60.5,4553980674,4109,1592,63.2,438450,96,119,20220806
9,10,10,0,NEW,20211792,헌트,2022-08-10,32089200,0.3,32089200,100,135753200,2543,2543,100,14196,10,10,20220806
0,1,1,0,OLD,20209343,한산: 용의 출현,2022-07-27,4580867431,47.1,-252837959,-5.2,46982113465,440821,-24597,-5.3,4598499,1638,6769,20220807
1,2,2,0,OLD,20196410,비상선언,2022-08-03,2937124308,30.2,-512947993,-14.9,14080742091,278728,-45752,-14.1,1397967,1588,6619,20220807
2,3,3,0,OLD,20194376,탑건: 매버릭,2022-06-22,747989164,7.7,-65835336,-8.1,79467607538,68710,-5641,-7.6,7448890,632,1304,20220807
3,4,4,0,OLD,20205362,미니언즈2,2022-07-20,665222085,6.8,-9931251,-1.5,19134385821,66780,-1266,-1.9,1972800,812,1721,20220807
4,5,5,0,OLD,20225190,뽀로로 극장판 드래곤캐슬 대모험,2022-07-28,264177800,2.7,1910901,0.7,3435645867,27591,172,0.6,367157,573,860,20220807
5,6,6,1,OLD,20209654,헤어질 결심,2022-06-29,169174033,1.7,-32677140,-16.2,18385204948,15203,-2798,-15.5,1775050,266,426,20220807
6,7,7,-1,OLD,20208446,외계+인 1부,2022-07-20,123965118,1.3,-98324419,-44.2,15629890451,11690,-7177,-38,1496937,374,499,20220807
7,8,8,0,OLD,20226107,극장판 도라에몽: 진구의 우주소전쟁 리틀스타워즈 2021,2022-08-03,77727199,0.8,2170399,2.9,346276298,7903,248,3.2,36419,357,466,20220807
8,9,9,0,OLD,20225237,명탐정 코난: 할로윈의 신부,2022-07-13,44635198,0.5,623298,1.4,4598615872,4122,13,0.3,442572,91,115,20220807
9,10,10,0,OLD,20211792,헌트,2022-08-10,29793598,0.3,-2295602,-7.2,165546798,2377,-166,-6.5,16573,12,13,20220807

In [46]:
# 날짜는 시작날짜와 + 며칠 을 처리할지 결정할 수 있습니다.
# 1년치 데이터를 얻은 다음 to_csv나 to_excel로 저장해주세요.
start_datetime = datetime.datetime(2021, 8, 8) # 년 월 일 순으로 넣어줍니다.

# 반복문과 append를 이용해서 1년치 데이터를 요청해서 합쳐보세요.
# target_date 컬럼에 조회 날짜를 추가해주세요.
# 빈 데이터프레임을 하나 생성해놓고(pd.DataFrame())
merged_data = pd.DataFrame()
for idx in range(365):
    # 날짜를 문자로 변경
    target_date = start_datetime.strftime('%Y%m%d')
    
    api_key = "f5eef3421c602c6cb7ea224104795888" # 발급받은 키만 복붙하세요
    request_date = target_date # 조회날짜를  xxxxyydd 20220623 형식으로 넣어주세요
    url = "http://kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key=%s&targetDt=%s" % (api_key, request_date)
    # 위의 url 변수를 이용해 데이터를 요청합니다.
    r = urllib.request.urlopen(url)

    # 요청 페이지의 결과 데이터를 파이썬 내부 데이터로 바꿉니다.
    json_raw = r.read()
    
    json_utf8 = json_raw.decode("utf-8")
    # json.loads(딕셔너리 형태의 문자열 자료)
    # 딕셔너리 형태로 적힌 문자열 자료를 딕셔너리형으로 변환
    json_complete = json.loads(json_utf8)
    box_result = pd.json_normalize(json_complete['boxOfficeResult']['dailyBoxOfficeList'])
    # box_result에 날짜 컬럼 추가해 날짜 정보 넣기
    box_result['date'] = request_date
    merged_data = pd.concat([merged_data, box_result])
    # 해당 날짜 데이터를 가져와 통합한 뒤에는 날짜를 하루 더해주기
    start_datetime = start_datetime + datetime.timedelta(days=1)
    print("%s일차 자료 수집 완료" % idx)
    # 너무 자주 크롤링시 블록먹을 가능성이 있음.
    time.sleep(1)
    
merged_data

0일차 자료 수집 완료
1일차 자료 수집 완료
2일차 자료 수집 완료
3일차 자료 수집 완료
4일차 자료 수집 완료
5일차 자료 수집 완료
6일차 자료 수집 완료
7일차 자료 수집 완료
8일차 자료 수집 완료
9일차 자료 수집 완료
10일차 자료 수집 완료
11일차 자료 수집 완료
12일차 자료 수집 완료
13일차 자료 수집 완료
14일차 자료 수집 완료
15일차 자료 수집 완료
16일차 자료 수집 완료
17일차 자료 수집 완료
18일차 자료 수집 완료
19일차 자료 수집 완료
20일차 자료 수집 완료
21일차 자료 수집 완료
22일차 자료 수집 완료
23일차 자료 수집 완료
24일차 자료 수집 완료
25일차 자료 수집 완료
26일차 자료 수집 완료
27일차 자료 수집 완료
28일차 자료 수집 완료
29일차 자료 수집 완료
30일차 자료 수집 완료
31일차 자료 수집 완료
32일차 자료 수집 완료
33일차 자료 수집 완료
34일차 자료 수집 완료
35일차 자료 수집 완료
36일차 자료 수집 완료
37일차 자료 수집 완료
38일차 자료 수집 완료
39일차 자료 수집 완료
40일차 자료 수집 완료
41일차 자료 수집 완료
42일차 자료 수집 완료
43일차 자료 수집 완료
44일차 자료 수집 완료
45일차 자료 수집 완료
46일차 자료 수집 완료
47일차 자료 수집 완료
48일차 자료 수집 완료
49일차 자료 수집 완료
50일차 자료 수집 완료
51일차 자료 수집 완료
52일차 자료 수집 완료
53일차 자료 수집 완료
54일차 자료 수집 완료
55일차 자료 수집 완료
56일차 자료 수집 완료
57일차 자료 수집 완료
58일차 자료 수집 완료
59일차 자료 수집 완료
60일차 자료 수집 완료
61일차 자료 수집 완료
62일차 자료 수집 완료
63일차 자료 수집 완료
64일차 자료 수집 완료
65일차 자료 수집 완료
66일차 자료 수집 완료
67일차 자료 수집 완료
68일차 자료 수집 완료
69일차 자료 수집 완료
70일차 자료 수집 완료
71일차 자료 수집 완료
72일차 자료 수집 완료
73일차 자료 수집 완료
74일차 자료 수집 완료
75일차 자료 수집 완료
76일차 자료 수집 완료
77일차 자료 수집 완료
78일차 자료 수집 완료
79일차 자료 수집 완료
80일차 자료 수집 완료
81일차 자료 수집 완료
82일차 자료 수집 완료
83일차 자료 수집 완료
84일차 자료 수집 완료
85일차 자료 수집 완료
86일차 자료 수집 완료
87일차 자료 수집 완료
88일차 자료 수집 완료
89일차 자료 수집 완료
90일차 자료 수집 완료
91일차 자료 수집 완료
92일차 자료 수집 완료
93일차 자료 수집 완료
94일차 자료 수집 완료
95일차 자료 수집 완료
96일차 자료 수집 완료
97일차 자료 수집 완료
98일차 자료 수집 완료
99일차 자료 수집 완료
100일차 자료 수집 완료
101일차 자료 수집 완료
102일차 자료 수집 완료
103일차 자료 수집 완료
104일차 자료 수집 완료
105일차 자료 수집 완료
106일차 자료 수집 완료
107일차 자료 수집 완료
108일차 자료 수집 완료
109일차 자료 수집 완료
110일차 자료 수집 완료
111일차 자료 수집 완료
112일차 자료 수집 완료
113일차 자료 수집 완료
114일차 자료 수집 완료
115일차 자료 수집 완료
116일차 자료 수집 완료
117일차 자료 수집 완료
118일차 자료 수집 완료
119일차 자료 수집 완료
120일차 자료 수집 완료
121일차 자료 수집 완료
122일차 자료 수집 완료
123일차 자료 수집 완료
124일차 자료 수집 완료
125일차 자료 수집 완료
126일차 자료 수집 완료
127일차 자료 수집 완료
128일차 자료 수집 완료
129일차 자료 수집 완료
130일차 자료 수집 완료
131일차 자료 수집 완료
132일차 자료 수집 완료
133일차 자료 수집 완료
134일차 자료 수집 완료
135일차 자료 수집 완료
136일차 자료 수집 완료
137일차 자료 수집 완료
138일차 자료 수집 완료
139일차 자료 수집 완료
140일차 자료 수집 완료
141일차 자료 수집 완료
142일차 자료 수집 완료
143일차 자료 수집 완료
144일차 자료 수집 완료
145일차 자료 수집 완료
146일차 자료 수집 완료
147일차 자료 수집 완료
148일차 자료 수집 완료
149일차 자료 수집 완료
150일차 자료 수집 완료
151일차 자료 수집 완료
152일차 자료 수집 완료
153일차 자료 수집 완료
154일차 자료 수집 완료
155일차 자료 수집 완료
156일차 자료 수집 완료
157일차 자료 수집 완료
158일차 자료 수집 완료
159일차 자료 수집 완료
160일차 자료 수집 완료
161일차 자료 수집 완료
162일차 자료 수집 완료
163일차 자료 수집 완료
164일차 자료 수집 완료
165일차 자료 수집 완료
166일차 자료 수집 완료
167일차 자료 수집 완료
168일차 자료 수집 완료
169일차 자료 수집 완료
170일차 자료 수집 완료
171일차 자료 수집 완료
172일차 자료 수집 완료
173일차 자료 수집 완료
174일차 자료 수집 완료
175일차 자료 수집 완료
176일차 자료 수집 완료
177일차 자료 수집 완료
178일차 자료 수집 완료
179일차 자료 수집 완료
180일차 자료 수집 완료
181일차 자료 수집 완료
182일차 자료 수집 완료
183일차 자료 수집 완료
184일차 자료 수집 완료
185일차 자료 수집 완료
186일차 자료 수집 완료
187일차 자료 수집 완료
188일차 자료 수집 완료
189일차 자료 수집 완료
190일차 자료 수집 완료
191일차 자료 수집 완료
192일차 자료 수집 완료
193일차 자료 수집 완료
194일차 자료 수집 완료
195일차 자료 수집 완료
196일차 자료 수집 완료
197일차 자료 수집 완료
198일차 자료 수집 완료
199일차 자료 수집 완료
200일차 자료 수집 완료
201일차 자료 수집 완료
202일차 자료 수집 완료
203일차 자료 수집 완료
204일차 자료 수집 완료
205일차 자료 수집 완료
206일차 자료 수집 완료
207일차 자료 수집 완료
208일차 자료 수집 완료
209일차 자료 수집 완료
210일차 자료 수집 완료
211일차 자료 수집 완료
212일차 자료 수집 완료
213일차 자료 수집 완료
214일차 자료 수집 완료
215일차 자료 수집 완료
216일차 자료 수집 완료
217일차 자료 수집 완료
218일차 자료 수집 완료
219일차 자료 수집 완료
220일차 자료 수집 완료
221일차 자료 수집 완료
222일차 자료 수집 완료
223일차 자료 수집 완료
224일차 자료 수집 완료
225일차 자료 수집 완료
226일차 자료 수집 완료
227일차 자료 수집 완료
228일차 자료 수집 완료
229일차 자료 수집 완료
230일차 자료 수집 완료
231일차 자료 수집 완료
232일차 자료 수집 완료
233일차 자료 수집 완료
234일차 자료 수집 완료
235일차 자료 수집 완료
236일차 자료 수집 완료
237일차 자료 수집 완료
238일차 자료 수집 완료
239일차 자료 수집 완료
240일차 자료 수집 완료
241일차 자료 수집 완료
242일차 자료 수집 완료
243일차 자료 수집 완료
244일차 자료 수집 완료
245일차 자료 수집 완료
246일차 자료 수집 완료
247일차 자료 수집 완료
248일차 자료 수집 완료
249일차 자료 수집 완료
250일차 자료 수집 완료
251일차 자료 수집 완료
252일차 자료 수집 완료
253일차 자료 수집 완료
254일차 자료 수집 완료
255일차 자료 수집 완료
256일차 자료 수집 완료
257일차 자료 수집 완료
258일차 자료 수집 완료
259일차 자료 수집 완료
260일차 자료 수집 완료
261일차 자료 수집 완료
262일차 자료 수집 완료
263일차 자료 수집 완료
264일차 자료 수집 완료
265일차 자료 수집 완료
266일차 자료 수집 완료
267일차 자료 수집 완료
268일차 자료 수집 완료
269일차 자료 수집 완료
270일차 자료 수집 완료
271일차 자료 수집 완료
272일차 자료 수집 완료
273일차 자료 수집 완료
274일차 자료 수집 완료
275일차 자료 수집 완료
276일차 자료 수집 완료
277일차 자료 수집 완료
278일차 자료 수집 완료
279일차 자료 수집 완료
280일차 자료 수집 완료
281일차 자료 수집 완료
282일차 자료 수집 완료
283일차 자료 수집 완료
284일차 자료 수집 완료
285일차 자료 수집 완료
286일차 자료 수집 완료
287일차 자료 수집 완료
288일차 자료 수집 완료
289일차 자료 수집 완료
290일차 자료 수집 완료
291일차 자료 수집 완료
292일차 자료 수집 완료
293일차 자료 수집 완료
294일차 자료 수집 완료
295일차 자료 수집 완료
296일차 자료 수집 완료
297일차 자료 수집 완료
298일차 자료 수집 완료
299일차 자료 수집 완료
300일차 자료 수집 완료
301일차 자료 수집 완료
302일차 자료 수집 완료
303일차 자료 수집 완료
304일차 자료 수집 완료
305일차 자료 수집 완료
306일차 자료 수집 완료
307일차 자료 수집 완료
308일차 자료 수집 완료
309일차 자료 수집 완료
310일차 자료 수집 완료
311일차 자료 수집 완료
312일차 자료 수집 완료
313일차 자료 수집 완료
314일차 자료 수집 완료
315일차 자료 수집 완료
316일차 자료 수집 완료
317일차 자료 수집 완료
318일차 자료 수집 완료
319일차 자료 수집 완료
320일차 자료 수집 완료
321일차 자료 수집 완료
322일차 자료 수집 완료
323일차 자료 수집 완료
324일차 자료 수집 완료
325일차 자료 수집 완료
326일차 자료 수집 완료
327일차 자료 수집 완료
328일차 자료 수집 완료
329일차 자료 수집 완료
330일차 자료 수집 완료
331일차 자료 수집 완료
332일차 자료 수집 완료
333일차 자료 수집 완료
334일차 자료 수집 완료
335일차 자료 수집 완료
336일차 자료 수집 완료
337일차 자료 수집 완료
338일차 자료 수집 완료
339일차 자료 수집 완료
340일차 자료 수집 완료
341일차 자료 수집 완료
342일차 자료 수집 완료
343일차 자료 수집 완료
344일차 자료 수집 완료
345일차 자료 수집 완료
346일차 자료 수집 완료
347일차 자료 수집 완료
348일차 자료 수집 완료
349일차 자료 수집 완료
350일차 자료 수집 완료
351일차 자료 수집 완료
352일차 자료 수집 완료
353일차 자료 수집 완료
354일차 자료 수집 완료
355일차 자료 수집 완료
356일차 자료 수집 완료
357일차 자료 수집 완료
358일차 자료 수집 완료
359일차 자료 수집 완료
360일차 자료 수집 완료
361일차 자료 수집 완료
362일차 자료 수집 완료
363일차 자료 수집 완료
364일차 자료 수집 완료

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,salesChange,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,date
0,1,1,0,OLD,20204117,모가디슈,2021-07-28,2000829380,56.5,38859180,2,16579074530,196672,4041,2.1,1712375,1639,6757,20210808
1,2,2,0,OLD,20217845,더 수어사이드 스쿼드,2021-08-04,676797240,19.1,-127499190,-15.9,2942253950,63095,-12197,-16.2,281377,1033,3306,20210808
2,3,3,0,OLD,20218391,보스 베이비 2,2021-07-21,284206020,8.0,1506480,0.5,7511398580,30046,108,0.4,836805,777,1654,20210808
3,4,4,0,OLD,20191951,블랙 위도우,2021-07-07,194489780,5.5,-28197330,-12.7,29457331370,18740,-2673,-12.5,2908679,540,924,20210808
4,5,5,0,OLD,20218875,극장판 도라에몽: 진구의 신공룡,2021-08-05,88917620,2.5,-4415810,-4.7,337195080,9837,-612,-5.9,38669,502,781,20210808
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,6,6,1,OLD,20209654,헤어질 결심,2022-06-29,169174033,1.7,-32677140,-16.2,18385204948,15203,-2798,-15.5,1775050,266,426,20220807
6,7,7,-1,OLD,20208446,외계+인 1부,2022-07-20,123965118,1.3,-98324419,-44.2,15629890451,11690,-7177,-38,1496937,374,499,20220807
7,8,8,0,OLD,20226107,극장판 도라에몽: 진구의 우주소전쟁 리틀스타워즈 2021,2022-08-03,77727199,0.8,2170399,2.9,346276298,7903,248,3.2,36419,357,466,20220807
8,9,9,0,OLD,20225237,명탐정 코난: 할로윈의 신부,2022-07-13,44635198,0.5,623298,1.4,4598615872,4122,13,0.3,442572,91,115,20220807
9,10,10,0,OLD,20211792,헌트,2022-08-10,29793598,0.3,-2295602,-7.2,165546798,2377,-166,-6.5,16573,12,13,20220807

In [56]:
# 스크린당 평균 관객이 제일 많았던 영화를 뽑아주세요.
# 관객 총합 / 스크린 총합 = 스크린당 관객이 나옵니다.
# 컬럼 타입이 object이므로, 집계함수를 쓸 수 있도록 int로 컬럼 전체 자료형을 바꿔줘야 합니다.
# 현재 수치데이터도 전부 문자로 간주되고 있기 때문에 int로 자료형을 바꿔서 계산해야함
merged_data['audiCnt'] = merged_data['audiCnt'].astype(int)
merged_data['scrnCnt'] = merged_data['scrnCnt'].astype(int)

In [57]:
merged_data.pivot_table(index='movieNm', values=['audiCnt','scrnCnt'], aggfunc='sum').sort_values(by='audiCnt', ascending=False)

                      audiCnt  scrnCnt
movieNm
범죄도시 2               12686014    81645
스파이더맨: 노 웨이 홈         7541536    90668
탑건: 매버릭               7448600    57863
닥터 스트레인지: 대혼돈의 멀티버스   5880700    48993
한산: 용의 출현             4597839    22656
...                       ...      ...
지지                        334        1
포 언투 어스                   300        1
맛있는 여동생                   259       20
아이 스틸 빌리브                 217        2
미싱타는 여자들                  201        1

[303 rows x 2 columns]